### ISSUE TITLE
Importing DbParms

### ISSUE THREAD

**Issue by Tall-KU-RideOn** [tcgoetz/GarminDB#113]
**Describe the bug**
When running `make setup`, I get the following error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tallku/Repo/GarminDB/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
ImportError: cannot import name 'DbParams' from 'utilities' (unknown location)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tallku/Repo/GarminDB/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
```

![image](https://user-images.githubusercontent.com/62021593/109717403-9ebf8200-7b6b-11eb-93fe-fe91483d9434.png)

**Expected behavior**

**Logs**
When running `make bugreport`, I get errors
```
Getting GarminDB version
Traceback (most recent call last):
  File "garmin.py", line 27, in <module>
    from import_garmin_activities import GarminJsonSummaryData, GarminJsonDetailsData, GarminTcxData, GarminActivitiesFitData
  File "/Users/tallku/Repo/GarminDB/import_garmin_activities.py", line 17, in <module>
    from garmin_db_tcx import GarminDbTcx
  File "/Users/tallku/Repo/GarminDB/garmin_db_tcx.py", line 8, in <module>
    from cached_property import cached_property
ModuleNotFoundError: No module named 'cached_property'
Zipping up bugreport.txt and logs
  adding: bugreport.txt (deflated 26%)
```

**Comment by Tall-KU-RideOn** [comment]
@wmbaum @tcgoetz @Grimler91  - I am getting all types of errors when just simply running `make setup`.  Does this use Python2.7?  Or Python 3?

**Comment by tcgoetz** [comment]
>  Does this use Python2.7?  Or Python 3?

3.x tested on 3.7.5
