### ISSUE TITLE
got an unexpected keyword argument 'aditional_headers'

### ISSUE THREAD

**Issue by lpierron** [tcgoetz/GarminDB#116]
```
make
___Downloading All Data___
Traceback (most recent call last):
  File "/Users/pierron/Developpements/GARMIN/GarminDB/garmin.py", line 341, in <module>
    main(sys.argv[1:])
  File "/Users/pierron/Developpements/GARMIN/GarminDB/garmin.py", line 322, in main
    download_data(args.overwrite, args.latest, args.stats)
  File "/Users/pierron/Developpements/GARMIN/GarminDB/garmin.py", line 114, in download_data
    download = Download()
  File "/Users/pierron/Developpements/GARMIN/GarminDB/download_garmin.py", line 64, in __init__
    self.sso_rest_client = RestClient(self.session, 'sso.garmin.com', 'sso', aditional_headers=self.garmin_headers)
TypeError: __init__() got an unexpected keyword argument 'aditional_headers'
```

**Comment by tcgoetz** [comment]
There is is the current version: https://github.com/tcgoetz/utilities/blob/672fb386161fc9cce1545ea89bc61248a3c95fa0/rest_client.py#L75

Your utilities submodule is out of date. You need to update the submodules when you update the main repo: make update
