### ISSUE TITLE
Cannot get to run

### ISSUE THREAD

**Issue by jhavens12** [tcgoetz/GarminDB#12]
I tried starting over from scratch and cannot get your program to run. When I run it the first time - I get this result:

> python analyze_garmin.py -S22:00,06:00  --sqlite /Users/tgoetz/HealthData/DBs
> analyze_garmin.py -s <sqlite db path> -m ...
> python import_garmin.py -e --sleep_input_dir "/Users/USER/HealthData/Sleep" --sqlite /Users/USER/HealthData/DBs
> INFO:import_garmin.py:Debug: False
> INFO:/Users/USER/Documents/GitHub/GarminDB/FileProcessor.py:Reading directory: /Users/USER/HealthData/Sleep
> python import_garmin.py -e --weight_input_dir "/Users/USER/HealthData/Weight" --sqlite /Users/USER/HealthData/DBs
> INFO:import_garmin.py:Debug: False English units: True
> INFO:/Users/USER/Documents/GitHub/GarminDB/FileProcessor.pyc:Reading directory: /Users/USER/HealthData/Weight
> python import_garmin.py -e --rhr_input_dir "/Users/USER/HealthData/RHR" --sqlite /Users/USER/HealthData/DBs
> INFO:import_garmin.py:Debug: False
> INFO:/Users/USER/Documents/GitHub/GarminDB/FileProcessor.pyc:Reading directory: /Users/USER/HealthData/RHR
> for dir in /Users/USER/HealthData/FitFiles/2018_Monitoring/; do \
> 		python import_garmin.py -e --fit_input_dir "$dir" --sqlite /Users/USER/HealthData/DBs; \
> 	done
> INFO:import_garmin.py:Debug: False English units: True
> INFO:/Users/USER/Documents/GitHub/GarminDB/FileProcessor.pyc:Reading directory: /Users/USER/HealthData/FitFiles/2018_Monitoring/
> python import_garmin_activities.py -e --input_dir "/Users/USER/HealthData/FitFiles/Activities" --sqlite /Users/USER/HealthData/DBs
> INFO:import_garmin_activities.py:Debug: 0
> INFO:/Users/USER/Documents/GitHub/GarminDB/FileProcessor.pyc:Reading directory: /Users/USER/HealthData/FitFiles/Activities
> INFO:import_garmin_activities.py:Debug: 0 English units: True
> INFO:/Users/USER/Documents/GitHub/GarminDB/FileProcessor.pyc:Reading directory: /Users/USER/HealthData/FitFiles/Activities
> INFO:import_garmin_activities.py:Debug: 0 English units: True
> INFO:/Users/USER/Documents/GitHub/GarminDB/FileProcessor.pyc:Reading directory: /Users/USER/HealthData/FitFiles/Activities
> python analyze_garmin.py --analyze --dates --sqlite /Users/USER/HealthData/DBs
> INFO:GarminDB.GarminDB:GarminDB: {'db_type': 'sqlite', 'db_path': '/Users/USER/HealthData/DBs'} debug: -1 
> INFO:GarminDB.MonitoringDB:MonitoringDB: {'db_type': 'sqlite', 'db_path': '/Users/USER/HealthData/DBs'} debug: -1 
> INFO:GarminDB.GarminSummaryDB:GarminSummaryDB: {'db_type': 'sqlite', 'db_path': '/Users/USER/HealthData/DBs'} debug: -1 
> INFO:HealthDB.SummaryDB:SummaryDB: {'db_type': 'sqlite', 'db_path': '/Users/USER/HealthData/DBs'} debug: -1 
> INFO:GarminDB.ActivitiesDB:ActivitiesDB: {'db_type': 'sqlite', 'db_path': '/Users/USER/HealthData/DBs'} debug: -1 
> INFO:analyze_garmin.py:File records: 0
> INFO:analyze_garmin.py:tcx files: 0
> INFO:analyze_garmin.py:activity files: 0
> INFO:analyze_garmin.py:monitoring_b files: 0
> INFO:analyze_garmin.py:Weight records: 0
> INFO:analyze_garmin.py:Max Weight: None
> INFO:analyze_garmin.py:Min Weight: None
> INFO:analyze_garmin.py:Avg Weight: None
> INFO:analyze_garmin.py:Latest Weight: None
> INFO:analyze_garmin.py:Stress records: 0
> INFO:analyze_garmin.py:Max Stress: None
> INFO:analyze_garmin.py:Min Stress: None
> INFO:analyze_garmin.py:Avg Stress: None
> INFO:analyze_garmin.py:Latest Stress: None
> INFO:analyze_garmin.py:RHR records: 0
> INFO:analyze_garmin.py:Max RHR: None
> INFO:analyze_garmin.py:Min RHR: None
> INFO:analyze_garmin.py:Avg RHR: None
> INFO:analyze_garmin.py:Latest RHR: None
> INFO:analyze_garmin.py:Sleep records: 0
> INFO:analyze_garmin.py:Max Sleep: None
> INFO:analyze_garmin.py:Min Sleep: None
> INFO:analyze_garmin.py:Avg Sleep: None
> INFO:analyze_garmin.py:Latest Sleep: None
> INFO:analyze_garmin.py:Activity summary records: 0
> INFO:analyze_garmin.py:Activities lap records: 0
> INFO:analyze_garmin.py:Activity records: 0
> INFO:analyze_garmin.py:Activities years: 0 ([])
> INFO:analyze_garmin.py:Running activities: 0
> INFO:analyze_garmin.py:Walking activities: 0
> INFO:analyze_garmin.py:Cycling activities: 0
> INFO:analyze_garmin.py:Mountain_Biking activities: 0
> INFO:analyze_garmin.py:Hiking activities: 0
> INFO:analyze_garmin.py:Elliptical activities: 0
> INFO:analyze_garmin.py:Treadmill_Running activities: 0
> INFO:analyze_garmin.py:Paddling activities: 0
> INFO:analyze_garmin.py:Resort_Skiing_Snowboarding activities: 0
> INFO:analyze_garmin.py:Monitoring records: 0
> INFO:analyze_garmin.py:Monitoring Years (0): []
> Traceback (most recent call last):
>   File "analyze_garmin.py", line 283, in <module>
>     main(sys.argv[1:])
>   File "analyze_garmin.py", line 280, in main
>     analyze.summary()
>   File "analyze_garmin.py", line 198, in summary
>     sleep_period_start = GarminDB.Attributes.get_time(self.garmindb, 'sleep_time')
>   File "/Users/USER/Documents/GitHub/GarminDB/HealthDB/DB.py", line 472, in get_time
>     return datetime.datetime.strptime(cls.get(db, key), "%H:%M:%S").time()
> TypeError: must be string, not None
> make: *** [garmin_summary] Error 1

I'm not sure if Garmin changed something or the scripts no longer work. Thanks!

**Comment by tcgoetz** [comment]
Should be fixed with above commit.
