### ISSUE TITLE
no module GarminConnectEnums

### ISSUE THREAD

**Issue by benbowen** [tcgoetz/GarminDB#15]
Is this missing from source or separate repo?

```
python import_garmin_activities.py -e -l --input_dir "/Users/bpb/HealthData/FitFiles/Activities" --sqlite /Users/bpb/HealthData/DBs
Traceback (most recent call last):
  File "import_garmin_activities.py", line 13, in <module>
    import GarminConnectEnums
ImportError: No module named GarminConnectEnums
```

**Comment by tcgoetz** [comment]
My bad. That's a new file I forgot to add. Added. Pushed.

**Comment by benbowen** [comment]
that module thows the following error for me:

```
INFO:/Users/bpb/repos/garmin_activity/GarminDB/GarminConnectEnums.py:Unknown event type: {u'typeId': 9, u'typeKey': u'uncategorized', u'sortOrder': 10}
Traceback (most recent call last):
  File "import_garmin_activities.py", line 392, in <module>
    main(sys.argv[1:])
  File "import_garmin_activities.py", line 380, in main
    gjd.process_files(db_params_dict)
  File "import_garmin_activities.py", line 279, in process_files
    event = GarminConnectEnums.Event.from_json(json_data)
  File "/Users/bpb/repos/garmin_activity/GarminDB/GarminConnectEnums.py", line 23, in from_json
    return cls(json_event['typeId'])
  File "/Users/bpb/.local/lib/python2.7/site-packages/enum/__init__.py", line 347, in __call__
    return cls.__new__(cls, value)
  File "/Users/bpb/.local/lib/python2.7/site-packages/enum/__init__.py", line 662, in __new__
    raise ValueError("%s is not a valid %s" % (value, cls.__name__))
ValueError: 9 is not a valid Event
make: *** [import_new_activities] Error 1
```

**Comment by tcgoetz** [comment]
Cool! That's actually a missing value from the event enum since I don't have any activities of type 'uncategorized'. I'll add it in a second.

**Comment by tcgoetz** [comment]
pushed

**Comment by benbowen** [comment]
Thanks!

**Comment by tcgoetz** [comment]
If you find some info for one of the unknown message or fields, open another bug for it. Sometime you can figure out what a field is based on comparing it to other known fields. Timestamp are all similar values.
