### ISSUE TITLE
Raspberry pi installation problems

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaron** [tcgoetz/GarminDB#153]
**Describe the bug**
Numpy error on Raspberry pi installation

**Logs**

pi@raspberrypi:~/GarminDB $ make create_dbs
garmindb_cli.py --all --download --import --analyze
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/garmindb_cli.py", line 22, in <module>
    from garmindb import python_version_check, log_version, format_version
  File "/home/pi/.local/lib/python3.9/site-packages/garmindb/__init__.py", line 27, in <module>
    from .graphs import Graph
  File "/home/pi/.local/lib/python3.9/site-packages/garmindb/graphs.py", line 14, in <module>
    import matplotlib.pyplot as plt
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/__init__.py", line 104, in <module>
    import numpy
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory

make: *** [Makefile:180: garmin] Error 1

**Please run bugreport.sh and attach bugreport.zip.**
Not possible to run:
pi@raspberrypi:~/GarminDB $ make bugreport
./bugreport.sh
/usr/bin/bash: line 1: ./bugreport.sh: No such file or directory
make: *** [Makefile:291: bugreport] Error 127

**Comment by tcgoetz** [comment]
This isn't a GarminDB issue. You need to debug your installation on why numpy isn't installing correctly. Numpy is a separate package that is a dependency of GarminDb.

**Comment by tcgoetz** [comment]
Graph functions have been moved out of the main package. This should no longer be a dependency.
