### ISSUE TITLE
KeyError: 'WELLNESS_RESTING_HEART_RATE'

### ISSUE THREAD

**Issue by benbowen** [tcgoetz/GarminDB#16]
Looks like Garmin might not store RHR the same way in the past

```
python download_garmin.py --sqlite /Users/bpb/HealthData/DBs -u ben.bowen@gmail.com -p Garmin1066 -r "/Users/bpb/HealthData/RHR"
INFO:root:get_rhr
INFO:root:get_rhr_chunk: 2018-08-22 - 2018-09-21
INFO:root:get_rhr_chunk: 2018-07-23 - 2018-08-22
INFO:root:get_rhr_chunk: 2018-06-23 - 2018-07-23
INFO:root:get_rhr_chunk: 2018-05-24 - 2018-06-23
INFO:root:get_rhr_chunk: 2018-04-24 - 2018-05-24
INFO:root:get_rhr_chunk: 2018-03-25 - 2018-04-24
INFO:root:get_rhr_chunk: 2018-02-23 - 2018-03-25
INFO:root:get_rhr_chunk: 2018-01-24 - 2018-02-23
INFO:root:get_rhr_chunk: 2017-12-25 - 2018-01-24
INFO:root:get_rhr_chunk: 2017-11-25 - 2017-12-25
INFO:root:get_rhr_chunk: 2017-10-26 - 2017-11-25
INFO:root:get_rhr_chunk: 2017-09-26 - 2017-10-26
INFO:root:get_rhr_chunk: 2017-08-27 - 2017-09-26
INFO:root:get_rhr_chunk: 2017-07-28 - 2017-08-27
INFO:root:get_rhr_chunk: 2017-06-28 - 2017-07-28
INFO:root:get_rhr_chunk: 2017-05-29 - 2017-06-28
INFO:root:get_rhr_chunk: 2017-04-29 - 2017-05-29
INFO:root:get_rhr_chunk: 2017-03-30 - 2017-04-29
INFO:root:get_rhr_chunk: 2017-02-28 - 2017-03-30
INFO:root:get_rhr_chunk: 2017-01-29 - 2017-02-28
INFO:root:get_rhr_chunk: 2016-12-30 - 2017-01-29
INFO:root:get_rhr_chunk: 2016-11-30 - 2016-12-30
INFO:root:get_rhr_chunk: 2016-10-31 - 2016-11-30
Traceback (most recent call last):
  File "download_garmin.py", line 428, in <module>
    main(sys.argv[1:])
  File "download_garmin.py", line 424, in main
    download.save_json_file(rhr + '/rhr_' + str(int(time.time())), download.get_rhr())
  File "download_garmin.py", line 266, in get_rhr
    chunk_data = self.get_rhr_chunk(start, end)
  File "download_garmin.py", line 256, in get_rhr_chunk
    rhr_data = response.json()['allMetrics']['metricsMap']['WELLNESS_RESTING_HEART_RATE']
KeyError: 'WELLNESS_RESTING_HEART_RATE'
make: *** [download_rhr] Error 1
```

**Comment by tcgoetz** [comment]
What does it log with the new code?

**Comment by benbowen** [comment]
I'm rebuilding my DB again with 600 day history.  It may be a while (maybe tomorrow) before I can test it again

**Comment by benbowen** [comment]
fixed
