### ISSUE TITLE
global name 'Exceptions' is not defined

### ISSUE THREAD

**Issue by benbowen** [tcgoetz/GarminDB#17]
Maybe download_garmin.py is missing a commit?

```
INFO:root:get_rhr
INFO:root:get_rhr_chunk: 2018-08-25 - 2018-09-24
INFO:root:get_rhr_chunk: 2018-07-26 - 2018-08-25
INFO:root:get_rhr_chunk: 2018-06-26 - 2018-07-26
INFO:root:get_rhr_chunk: 2018-05-27 - 2018-06-26
INFO:root:get_rhr_chunk: 2018-04-27 - 2018-05-27
INFO:root:get_rhr_chunk: 2018-03-28 - 2018-04-27
INFO:root:get_rhr_chunk: 2018-02-26 - 2018-03-28
INFO:root:get_rhr_chunk: 2018-01-27 - 2018-02-26
INFO:root:get_rhr_chunk: 2017-12-28 - 2018-01-27
INFO:root:get_rhr_chunk: 2017-11-28 - 2017-12-28
INFO:root:get_rhr_chunk: 2017-10-29 - 2017-11-28
INFO:root:get_rhr_chunk: 2017-09-29 - 2017-10-29
INFO:root:get_rhr_chunk: 2017-08-30 - 2017-09-29
INFO:root:get_rhr_chunk: 2017-07-31 - 2017-08-30
INFO:root:get_rhr_chunk: 2017-07-01 - 2017-07-31
INFO:root:get_rhr_chunk: 2017-06-01 - 2017-07-01
INFO:root:get_rhr_chunk: 2017-05-02 - 2017-06-01
INFO:root:get_rhr_chunk: 2017-04-02 - 2017-05-02
INFO:root:get_rhr_chunk: 2017-03-03 - 2017-04-02
INFO:root:get_rhr_chunk: 2017-02-01 - 2017-03-03
INFO:root:get_rhr_chunk: 2017-01-02 - 2017-02-01
INFO:root:get_rhr_chunk: 2016-12-03 - 2017-01-02
INFO:root:get_rhr_chunk: 2016-11-03 - 2016-12-03
Traceback (most recent call last):
  File "download_garmin.py", line 432, in <module>
    main(sys.argv[1:])
  File "download_garmin.py", line 428, in main
    download.save_json_file(rhr + '/rhr_' + str(int(time.time())), download.get_rhr())
  File "download_garmin.py", line 270, in get_rhr
    chunk_data = self.get_rhr_chunk(start, end)
  File "download_garmin.py", line 260, in get_rhr_chunk
    except Exceptions:
NameError: global name 'Exceptions' is not defined
make: *** [download_rhr] Error 1
```

**Comment by tcgoetz** [comment]
fix pushed

**Comment by benbowen** [comment]
it created a new one:

```
INFO:analyze_garmin.py:Days gap between 236 (2018-08-24 00:00:00) and 239 (2018-08-27 00:00:00)
Traceback (most recent call last):
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: float argument required, not NoneType
Logged from file analyze_garmin.py, line 242
Traceback (most recent call last):
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: float argument required, not NoneType
Logged from file analyze_garmin.py, line 246
Traceback (most recent call last):
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/bpb/anaconda2/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: float argument required, not NoneType
Logged from file analyze_garmin.py, line 250
```

**Comment by tcgoetz** [comment]
Fix pushed. That's something different.

Did you get a log out from the weight download for the error at the end of your data?

**Comment by benbowen** [comment]
Yes! No errors, Very detailed log output too.  I'll send a new ticket for each activity.
