### ISSUE TITLE
No module named 'PyInstaller.__main__'

### ISSUE THREAD

**Issue by mriamnobody** [tcgoetz/GarminDB#177]
I'm using Windows 11 and Python 3.10.7. I executed command `pip install -r requirements.txt`, but encountered the error `ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package`. At this point I have not installed garmindb using `pip install garmindb`

Command prompt Log:
```
(garmin) C:\Users\rosha\Downloads\Compressed\GarminDB-3.2.8>pip install -r requirements.txt
Collecting SQLAlchemy==1.4.42
  Downloading SQLAlchemy-1.4.42-cp310-cp310-win_amd64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 2.9 MB/s eta 0:00:00
Collecting requests==2.28.1
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB ? eta 0:00:00
Collecting python-dateutil==2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting cached-property==1.5.2
  Downloading cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting tqdm==4.64.1
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB ? eta 0:00:00
Collecting matplotlib==3.4.3
  Downloading matplotlib-3.4.3.tar.gz (37.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.9/37.9 MB 65.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting cloudscraper==1.2.58
  Downloading cloudscraper-1.2.58-py2.py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.3/96.3 kB ? eta 0:00:00
Collecting ipykernel==6.4.1
  Downloading ipykernel-6.4.1-py3-none-any.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.0/124.0 kB ? eta 0:00:00
Collecting fitfile==1.1.3
  Downloading fitfile-1.1.3-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.4/63.4 kB 3.3 MB/s eta 0:00:00
Collecting tcxfile==1.0.4
  Downloading tcxfile-1.0.4-py3-none-any.whl (12 kB)
Collecting idbutils==1.0.6
  Downloading idbutils-1.0.6-py3-none-any.whl (29 kB)
Collecting altgraph==0.17
  Downloading altgraph-0.17-py2.py3-none-any.whl (21 kB)
Collecting appnope==0.1.2
  Downloading appnope-0.1.2-py2.py3-none-any.whl (4.3 kB)
Collecting argon2-cffi==21.3.0
  Downloading argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting argon2-cffi-bindings==21.2.0
  Downloading argon2_cffi_bindings-21.2.0-cp36-abi3-win_amd64.whl (30 kB)
Collecting attrs==21.4.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB ? eta 0:00:00
Collecting backcall==0.2.0
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting bleach==3.3.0
  Downloading bleach-3.3.0-py2.py3-none-any.whl (283 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.5/283.5 kB ? eta 0:00:00
Collecting build==0.8.0
  Downloading build-0.8.0-py3-none-any.whl (17 kB)
Collecting certifi==2022.9.24
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB ? eta 0:00:00
Collecting cffi==1.15.0
  Downloading cffi-1.15.0-cp310-cp310-win_amd64.whl (180 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.3/180.3 kB ? eta 0:00:00
Collecting chardet==4.0.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.7/178.7 kB 11.2 MB/s eta 0:00:00
Collecting charset-normalizer==2.1.1
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting colorama==0.4.4
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting commonmark==0.9.1
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 kB ? eta 0:00:00
Collecting cycler==0.10.0
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting debugpy==1.4.3
  Downloading debugpy-1.4.3-py2.py3-none-any.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 10.2 MB/s eta 0:00:00
Collecting decorator==5.1.0
  Downloading decorator-5.1.0-py3-none-any.whl (9.1 kB)
Collecting defusedxml==0.7.1
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting docutils==0.17.1
  Downloading docutils-0.17.1-py2.py3-none-any.whl (575 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 575.5/575.5 kB 35.3 MB/s eta 0:00:00
Collecting entrypoints==0.3
  Downloading entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting flake8==5.0.4
  Downloading flake8-5.0.4-py2.py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB ? eta 0:00:00
Collecting greenlet==1.1.3.post0
  Downloading greenlet-1.1.3.post0-cp310-cp310-win_amd64.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.9/101.9 kB ? eta 0:00:00
Collecting idna==3.4
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting importlib-metadata==4.5.0
  Downloading importlib_metadata-4.5.0-py3-none-any.whl (17 kB)
Collecting ipyleaflet==0.15.0
  Downloading ipyleaflet-0.15.0-py2.py3-none-any.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 53.1 MB/s eta 0:00:00
Collecting ipython==7.27.0
  Downloading ipython-7.27.0-py3-none-any.whl (787 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.0/788.0 kB 48.6 MB/s eta 0:00:00
Collecting ipython-genutils==0.2.0
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting ipywidgets==7.6.5
  Downloading ipywidgets-7.6.5-py2.py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.8/121.8 kB ? eta 0:00:00
Collecting jedi==0.18.0
  Downloading jedi-0.18.0-py2.py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 45.3 MB/s eta 0:00:00
Collecting Jinja2==3.0.3
  Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 kB ? eta 0:00:00
Collecting jsonschema==4.4.0
  Downloading jsonschema-4.4.0-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.7/72.7 kB 2.0 MB/s eta 0:00:00
Collecting jupyter-client==7.0.3
  Downloading jupyter_client-7.0.3-py3-none-any.whl (122 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.0/123.0 kB ? eta 0:00:00
Collecting jupyter-core==4.8.1
  Downloading jupyter_core-4.8.1-py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.1/86.1 kB ? eta 0:00:00
Collecting jupyterlab-pygments==0.1.2
  Downloading jupyterlab_pygments-0.1.2-py2.py3-none-any.whl (4.6 kB)
Collecting jupyterlab-widgets==1.0.2
  Downloading jupyterlab_widgets-1.0.2-py3-none-any.whl (243 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.4/243.4 kB 15.5 MB/s eta 0:00:00
Collecting keyring==23.0.1
  Downloading keyring-23.0.1-py3-none-any.whl (33 kB)
Collecting kiwisolver==1.3.2
  Downloading kiwisolver-1.3.2-cp310-cp310-win_amd64.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.1/52.1 kB ? eta 0:00:00
Collecting macholib==1.14
  Downloading macholib-1.14-py2.py3-none-any.whl (37 kB)
Collecting MarkupSafe==2.0.1
  Downloading MarkupSafe-2.0.1-cp310-cp310-win_amd64.whl (15 kB)
Collecting matplotlib-inline==0.1.3
  Downloading matplotlib_inline-0.1.3-py3-none-any.whl (8.2 kB)
Collecting mccabe==0.7.0
  Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting mistune==0.8.4
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting nbclient==0.5.10
  Downloading nbclient-0.5.10-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.9/69.9 kB ? eta 0:00:00
Collecting nbconvert==6.4.1
  Downloading nbconvert-6.4.1-py3-none-any.whl (557 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.4/557.4 kB 34.2 MB/s eta 0:00:00
Collecting nbformat==5.1.3
  Downloading nbformat-5.1.3-py3-none-any.whl (178 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.9/178.9 kB ? eta 0:00:00
Collecting nest-asyncio==1.5.1
  Downloading nest_asyncio-1.5.1-py3-none-any.whl (5.0 kB)
Collecting notebook==6.4.8
  Downloading notebook-6.4.8-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 10.5 MB/s eta 0:00:00
Collecting numpy==1.21.2
  Downloading numpy-1.21.2.zip (10.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 29.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting packaging==20.9
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 2.0 MB/s eta 0:00:00
Collecting pandas==1.4.2
  Downloading pandas-1.4.2-cp310-cp310-win_amd64.whl (10.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 38.5 MB/s eta 0:00:00
Collecting pandocfilters==1.5.0
  Downloading pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting parso==0.8.2
  Downloading parso-0.8.2-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.0/94.0 kB 5.2 MB/s eta 0:00:00
Collecting pep517==0.10.0
  Downloading pep517-0.10.0-py2.py3-none-any.whl (19 kB)
Collecting pexpect==4.8.0
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 3.3 MB/s eta 0:00:00
Collecting pickleshare==0.7.5
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting Pillow==8.3.2
  Downloading Pillow-8.3.2-cp310-cp310-win_amd64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 5.9 MB/s eta 0:00:00
Collecting pkginfo==1.8.2
  Downloading pkginfo-1.8.2-py2.py3-none-any.whl (26 kB)
Collecting prometheus-client==0.13.1
  Downloading prometheus_client-0.13.1-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.1/57.1 kB ? eta 0:00:00
Collecting prompt-toolkit==3.0.20
  Downloading prompt_toolkit-3.0.20-py3-none-any.whl (370 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 370.7/370.7 kB 22.5 MB/s eta 0:00:00
Collecting ptyprocess==0.7.0
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting pycodestyle==2.9.1
  Downloading pycodestyle-2.9.1-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.5/41.5 kB ? eta 0:00:00
Collecting pycparser==2.21
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting pydocstyle==6.1.1
  Downloading pydocstyle-6.1.1-py3-none-any.whl (37 kB)
Collecting pyflakes==2.5.0
  Downloading pyflakes-2.5.0-py2.py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.1/66.1 kB ? eta 0:00:00
Collecting Pygments==2.10.0
  Downloading Pygments-2.10.0-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 32.4 MB/s eta 0:00:00
Collecting pyinstaller==4.3
  Downloading pyinstaller-4.3.tar.gz (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 47.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      Traceback (most recent call last):
        File "C:\Users\rosha\Downloads\Compressed\GarminDB-3.2.8\garmin\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\rosha\Downloads\Compressed\GarminDB-3.2.8\garmin\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\rosha\Downloads\Compressed\GarminDB-3.2.8\garmin\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 75, in <module>
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\dist.py", line 881, in parse_config_files
          setupcfg.parse_configuration(
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 186, in parse_configuration
          meta.parse()
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 504, in parse
          section_parser_method(section_options)
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 479, in parse_section
          self[name] = value
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 295, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 609, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 421, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\config\expand.py", line 194, in read_attr
          module = _load_spec(spec, module_name)
        File "C:\Users\rosha\AppData\Local\Temp\pip-build-env-h2kio_dm\overlay\Lib\site-packages\setuptools\config\expand.py", line 214, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "C:\Users\rosha\AppData\Local\Temp\pip-install-an5x549a\pyinstaller_85422f4b4ff64a4e809c3e6bb349e710\PyInstaller.py", line 16, in <module>
          from PyInstaller.__main__ import run
      ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tcgoetz** [comment]
`pip install garmindb` should be all you need. You don't need to run `pip install -r requirements.txt` to install the package

**Comment by tcgoetz** [comment]
pyinstaller is no longer used by the project
