### ISSUE TITLE
Downloading Database Fails since 9/25/2023

### ISSUE THREAD

**Issue by spartan-it** [tcgoetz/GarminDB#195]
**Describe the bug**
I have been running a pipeline where I download data every day from Garmin, but to my surprise, for the last two days, the process has been failing with the same error (see logs). I have not changed any files, especially `GarminConnectConfig.json`. 

**To Reproduce**
1. Create environment:
```
python3 -m venv garmin-env
```
2. Activate environment:
```
source garmin-env/bin/activate 
```
3. Install garmin db using pip:
```
pip install garmindb
```
4. Add proper authentication to `GarminConnectConfig.json` 
```
nano ~/.GarminDb/GarminConnectConfig.json
```
5. Run the following command (update only; I already have data from years before):
```
garmindb_cli.py --all --download --import --analyze --latest
```

**Expected behavior**
I should see how the data is being downloaded and no errors at the end.

**Logs**
```
Running command: source /home/diegoalesar/garmin-env/bin/activate && garmindb_cli.py --all --download --import --analyze --latest
[2023-09-26, 20:00:26 EDT] {ssh.py:522} INFO - ___Downloading Latest Data___
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING - Traceback (most recent call last):
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING -   File "/home/diegoalesar/garmin-env/bin/garmindb_cli.py", line 358, in <module>
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING -     main(sys.argv[1:])
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING -   File "/home/diegoalesar/garmin-env/bin/garmindb_cli.py", line 339, in main
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING -     download_data(args.overwrite, args.latest, args.stats)
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING -   File "/home/diegoalesar/garmin-env/bin/garmindb_cli.py", line 112, in download_data
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING -     if not download.login():
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING -   File "/home/diegoalesar/garmin-env/lib/python3.8/site-packages/garmindb/download.py", line 178, in login
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING -     self.display_name = self.user_prefs['displayName']
[2023-09-26, 20:00:28 EDT] {ssh.py:527} WARNING - TypeError: 'NoneType' object is not subscriptable
[2023-09-26, 20:00:29 EDT] {taskinstance.py:1824} ERROR - Task failed with exception
```
**Please run bugreport.sh and attach bugreport.zip.**
[bugreport.zip](https://github.com/tcgoetz/GarminDB/files/12739836/bugreport.zip)

**Additional context**
I have been running the pipeline for about a month. I haven't made any changes to any files. I tried starting from zero with no luck either. Using python 3.8.10

**Comment by amnid** [comment]
same issue

**Comment by smacrico** [comment]
i get the exatly same issue.. maybe garmin changed something to way of loign??

**Comment by matin** [comment]
This is related to the same issue discussed in https://github.com/pe-st/garmin-connect-export/issues/95. The issue can be resolved by migrating to [Garth](https://github.com/matin/garth) for the authentication (discussed in #192).

The discussion includes several examples of projects that performed the migration.

**Comment by smacrico** [comment]
> This is related to the same issue discussed in [pe-st/garmin-connect-export#95](https://github.com/pe-st/garmin-connect-export/issues/95). The issue can be resolved by migrating to [Garth](https://github.com/matin/garth) for the authentication (discussed in #192).
> 
> The discussion includes several examples of projects that performed the migration.

thanks for the info! tried the changes got a step further  of course with different authentication errors... Unfortunately i am not that good developer to fix this.. but i ll keep trying..

**Comment by tcgoetz** [comment]
The garth-migration branch is now working (auth, download, etc), but is not ready for merge yet.

**Comment by smacrico** [comment]
Next stop: release!! Thank you so much!!

**Comment by tcgoetz** [comment]
https://github.com/tcgoetz/GarminDB/releases/tag/v3.5.0

**Comment by spartan-it** [comment]
I can confirm is working now. Thank you very much for your hard work! I highly appreciate it!
