### ISSUE TITLE
Crashes when no data is available for date

### ISSUE THREAD

**Issue by benbowen** [tcgoetz/GarminDB#20]
I believe the current code is crashing when no data exists on server for a given date.  For example, today's date (I haven't synced my watch today).

```
INFO:root:get_monitoring_day: 2018-10-09
Traceback (most recent call last):
  File "download_garmin.py", line 445, in <module>
    main(sys.argv[1:])
  File "download_garmin.py", line 428, in main
    download.get_monitoring(date, days)
  File "download_garmin.py", line 176, in get_monitoring
    self.get_monitoring_day(day_date)
  File "download_garmin.py", line 168, in get_monitoring_day
    response = self.get(self.garmin_connect_download_daily_url + '/' + date.strftime("%Y-%m-%d"))
  File "download_garmin.py", line 76, in get
    response.raise_for_status()
  File "/Users/bpb/anaconda2/lib/python2.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://connect.garmin.com/modern/proxy/download-service/files/wellness/2018-10-09
make: *** [download_monitoring] Error 1

```

**Comment by benbowen** [comment]
Just as a record for testing purposes, here is another one:

```
INFO:root:get_monitoring_day: 2018-06-06
Traceback (most recent call last):
  File "download_garmin.py", line 445, in <module>
    main(sys.argv[1:])
  File "download_garmin.py", line 428, in main
    download.get_monitoring(date, days)
  File "download_garmin.py", line 176, in get_monitoring
    self.get_monitoring_day(day_date)
  File "download_garmin.py", line 168, in get_monitoring_day
    response = self.get(self.garmin_connect_download_daily_url + '/' + date.strftime("%Y-%m-%d"))
  File "download_garmin.py", line 76, in get
    response.raise_for_status()
  File "/Users/bpb/anaconda2/lib/python2.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://connect.garmin.com/modern/proxy/download-service/files/wellness/2018-06-06
make: *** [download_monitoring] Error 1
```

**Comment by tcgoetz** [comment]
Just pushed 9e79e06  for this.
