### ISSUE TITLE
Failed to parse Message DataMessage from WELLNESS fit files

### ISSUE THREAD

**Issue by alrjan** [tcgoetz/GarminDB#229]
**Describe the bug**
Before I talk about the bug, I just want to say how much I appreciate the work you have done here - even if this issue I'm having is just a "me" problem and I never get it resolved this project is still great, anyway...

When running "garmindb_cli.py --all --download --import --analyze --latest", the files get downloaded without issue and lots of data lands in the various Sqlite databases which is great, however I get lots of error messages similar to the below:

_Failed to parse /mnt/docker01/dockerdata/garmindb_data/FitFiles/Monitoring/2024/248794252902_WELLNESS.fit: Failed to parse Message DataMessage(<MessageType.monitoring_info: 103>: []): Failed to parse DataField [6, 1, 13] for Field ActivityTypeField (activity_type) : 13 is not a valid ActivityType_

It always seems to be ActivityType13, as an aside that may or may not be related within the garmin_monitoring.db, with exception of the _attributes table, all the other tables are empty.

**To Reproduce**
1. Run garmindb_cli.py --all --download --import --analyze --latest
2. Observe potential error messages relating to ActivityType 13

**Expected behavior**
ActivityType 13 to be parsed and included in the database as per all other ActivityTypes

**Logs**
_Here is a selection from the log file that I think is relevant_
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_message.py", line 68, in __init__
    data_field = DataField(fit_file, definition_message, definition_message.field_definitions[index], measurement_system)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_field.py", line 26, in __init__
    super().__init__(file, schema, None, definition_message.endian)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data.py", line 103, in __init__
    self._convert()
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_field.py", line 44, in _convert
    raise FitDataFieldParse(self.field_value, self.field, e)
fitfile.exceptions.exceptions.FitDataFieldParse: Failed to parse DataField [6, 1, 13] for Field ActivityTypeField (activity_type) : 13 is not a valid ActivityType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/garmindb/fit_data.py", line 51, in process_files
    fit_file = fitfile.file.File(file_name, self.measurement_system)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/file.py", line 46, in __init__
    self.__parse(file)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/file.py", line 71, in __parse
    data_message = DataMessage(definition_message, file, self.measurement_system, data_message_context)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_message.py", line 70, in __init__
    raise FitMessageParse(self, e)
fitfile.exceptions.exceptions.FitMessageParse: Failed to parse Message DataMessage(<MessageType.monitoring_info: 103>: []): Failed to parse DataField [6, 1, 13] for Field ActivityTypeField (activity_type) : 13 is not a valid ActivityType

ERROR:/usr/local/lib/python3.10/dist-packages/garmindb/fit_data.py:Failed to parse /mnt/docker01/dockerdata/garmindb_data/FitFiles/Monitoring/2024/248155628540_WELLNESS.fit: Failed to parse Message DataMessage(<MessageType.monitoring_info: 103>: []): Failed to parse DataField [6, 1, 13] for Field ActivityTypeField (activity_type) : 13 is not a valid ActivityType
ERROR:root:Failed to parse /mnt/docker01/dockerdata/garmindb_data/FitFiles/Monitoring/2024/248155628540_WELLNESS.fit: Failed to parse Message DataMessage(<MessageType.monitoring_info: 103>: []): Failed to parse DataField [6, 1, 13] for Field ActivityTypeField (activity_type) : 13 is not a valid ActivityType - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_field.py", line 42, in _convert
    self.values = self.field.convert(self.field_value, self.field_definition.invalid(), self.measurement_system)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/fields.py", line 71, in convert
    return [FieldValue(self, value, invalid, **{self._name: self._convert_many(value, invalid)})]
  File "/usr/local/lib/python3.10/dist-packages/fitfile/fields.py", line 66, in _convert_many
    return self.__convert_many(self._convert_single, value, invalid)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/fields.py", line 62, in __convert_many
    return [_convert_single(sub_value, invalid) for sub_value in value]
  File "/usr/local/lib/python3.10/dist-packages/fitfile/fields.py", line 62, in <listcomp>
    return [_convert_single(sub_value, invalid) for sub_value in value]
  File "/usr/local/lib/python3.10/dist-packages/fitfile/activity_fields.py", line 65, in _convert_single
    return ActivityType(value)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 13 is not a valid ActivityType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_message.py", line 68, in __init__
    data_field = DataField(fit_file, definition_message, definition_message.field_definitions[index], measurement_system)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_field.py", line 26, in __init__
    super().__init__(file, schema, None, definition_message.endian)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data.py", line 103, in __init__
    self._convert()
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_field.py", line 44, in _convert
    raise FitDataFieldParse(self.field_value, self.field, e)
fitfile.exceptions.exceptions.FitDataFieldParse: Failed to parse DataField [6, 1, 13] for Field ActivityTypeField (activity_type) : 13 is not a valid ActivityType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/garmindb/fit_data.py", line 51, in process_files
    fit_file = fitfile.file.File(file_name, self.measurement_system)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/file.py", line 46, in __init__
    self.__parse(file)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/file.py", line 71, in __parse
    data_message = DataMessage(definition_message, file, self.measurement_system, data_message_context)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_message.py", line 70, in __init__
    raise FitMessageParse(self, e)
fitfile.exceptions.exceptions.FitMessageParse: Failed to parse Message DataMessage(<MessageType.monitoring_info: 103>: []): Failed to parse DataField [6, 1, 13] for Field ActivityTypeField (activity_type) : 13 is not a valid ActivityType

INFO:root:skipping non-matching File(<UnknownEnumValue.UnknownEnumValue_73: 73> /mnt/docker01/dockerdata/garmindb_data/FitFiles/Monitoring/2024/248232287519_SKIN_TEMP.fit <UnknownEnumValue.UnknownEnumValue_73: 73> [<MessageType.file_id: 0>, <MessageType.file_creator: 49>, <MessageType.device_info: 23>, <UnknownMessageType.unknown_398: 398>] dev fields {})
INFO:root:skipping non-matching File(<FileType.metrics: 44> /mnt/docker01/dockerdata/garmindb_data/FitFiles/Monitoring/2024/248232249036_METRICS.fit FileType.metrics [<MessageType.file_id: 0>, <MessageType.file_creator: 49>, <MessageType.device_info: 23>, <MessageType.local_time: 241>, <UnknownMessageType.unknown_410: 410>, <MessageType.unknown_284: 284>] dev fields {})
ERROR:/usr/local/lib/python3.10/dist-packages/garmindb/fit_data.py:Failed to parse /mnt/docker01/dockerdata/garmindb_data/FitFiles/Monitoring/2024/248183741479_WELLNESS.fit: Failed to parse Message DataMessage(<MessageType.monitoring_info: 103>: []): Failed to parse DataField [6, 1, 13] for Field ActivityTypeField (activity_type) : 13 is not a valid ActivityType
ERROR:root:Failed to parse /mnt/docker01/dockerdata/garmindb_data/FitFiles/Monitoring/2024/248183741479_WELLNESS.fit: Failed to parse Message DataMessage(<MessageType.monitoring_info: 103>: []): Failed to parse DataField [6, 1, 13] for Field ActivityTypeField (activity_type) : 13 is not a valid ActivityType - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fitfile/data_field.py", line 42, in _convert
    self.values = self.field.convert(self.field_value, self.field_definition.invalid(), self.measurement_system)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/fields.py", line 71, in convert
    return [FieldValue(self, value, invalid, **{self._name: self._convert_many(value, invalid)})]
  File "/usr/local/lib/python3.10/dist-packages/fitfile/fields.py", line 66, in _convert_many
    return self.__convert_many(self._convert_single, value, invalid)
  File "/usr/local/lib/python3.10/dist-packages/fitfile/fields.py", line 62, in __convert_many
    return [_convert_single(sub_value, invalid) for sub_value in value]
  File "/usr/local/lib/python3.10/dist-packages/fitfile/fields.py", line 62, in <listcomp>
    return [_convert_single(sub_value, invalid) for sub_value in value]
  File "/usr/local/lib/python3.10/dist-packages/fitfile/activity_fields.py", line 65, in _convert_single
    return ActivityType(value)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 13 is not a valid ActivityType

**Comment by tcgoetz** [comment]
We need to figure out what ActivityType 13 is. Then I can add an entry for it.

**Comment by tcgoetz** [comment]
Release 3.6.1 doesn't have a value for activity type 13, but should not crash. Please verify.

**Comment by lostavar** [comment]
I started using your great project a few days ago. When importing wellness data using
`garmindb_cli.py --monitoring --import --latest`
I also get the error mentioned above:

> ERROR:/garmindb/lib/python3.11/site-packages/garmindb/fit_file_processor.py:Failed to write message <MessageType.monitoring_info: 103> type DataMessage(<MessageType.monitoring_info: 103>: [timestamp(datetime.datetime(2025, 12, 22, 20, 37, tzinfo=datetime.timezone.utc) (1135370220)), local_timestamp(datetime.datetime(2025, 12, 22, 21, 37) (1135373820)), cycles_to_distance([1.6652, 2.4978, 2.0] m/cycle ([8326, 12489, 10000])), cycles_to_calories([0.06972667144792413, 0.2199378436528807, 0.0] kcal/cycle ([350, 1104, 0])), unknown_7([7500.0, 7500.0, 2000.0, 2000.0]), resting_metabolic_rate(2316.0 kcal/day), activity_type([<ActivityType.walking: 6>, <ActivityType.running: 1>, <UnknownEnumValue.UnknownEnumValue_13: 13>] ([6, 1, 13])), unknown_8([invalid] (255))]): (builtins.LookupError) '<UnknownEnumValue.UnknownEnumValue_13: 13>' is not among the defined enum values. Enum name: activitytype. Possible values: generic, running, cycling, ..., invalid
[SQL: SELECT monitoring_info.timestamp AS monitoring_info_timestamp, monitoring_info.file_id AS monitoring_info_file_id, monitoring_info.activity_type AS monitoring_info_activity_type, monitoring_info.resting_metabolic_rate AS monitoring_info_resting_metabolic_rate, monitoring_info.cycles_to_distance AS monitoring_info_cycles_to_distance, monitoring_info.cycles_to_calories AS monitoring_info_cycles_to_calories 
FROM monitoring_info 
WHERE monitoring_info.timestamp = ? AND monitoring_info.activity_type = ?]
[parameters: [{}]]
ERROR:root:Failed to write message <MessageType.monitoring_info: 103> type DataMessage(<MessageType.monitoring_info: 103>: [timestamp(datetime.datetime(2025, 12, 22, 20, 37, tzinfo=datetime.timezone.utc) (1135370220)), local_timestamp(datetime.datetime(2025, 12, 22, 21, 37) (1135373820)), cycles_to_distance([1.6652, 2.4978, 2.0] m/cycle ([8326, 12489, 10000])), cycles_to_calories([0.06972667144792413, 0.2199378436528807, 0.0] kcal/cycle ([350, 1104, 0])), unknown_7([7500.0, 7500.0, 2000.0, 2000.0]), resting_metabolic_rate(2316.0 kcal/day), activity_type([<ActivityType.walking: 6>, <ActivityType.running: 1>, <UnknownEnumValue.UnknownEnumValue_13: 13>] ([6, 1, 13])), unknown_8([invalid] (255))]): Traceback (most recent call last):
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1657, in _db_value_for_elem
    return self._valid_lookup[elem]
           ~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: <UnknownEnumValue.UnknownEnumValue_13: 13>

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1811, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1483, in _init_compiled
    l_param: List[Any] = [
                         ^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1485, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1806, in process
    value = self._db_value_for_elem(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1670, in _db_value_for_elem
    raise LookupError(
LookupError: '<UnknownEnumValue.UnknownEnumValue_13: 13>' is not among the defined enum values. Enum name: activitytype. Possible values: generic, running, cycling, ..., invalid

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/garmindb/lib/python3.11/site-packages/garmindb/fit_file_processor.py", line 53, in __write_generic
    function(fit_file, message.fields)
  File "/garmindb/lib/python3.11/site-packages/garmindb/monitoring_fit_file_processor.py", line 58, in _write_monitoring_info_entry
    MonitoringInfo.s_insert_or_update(self.garmin_mon_db_session, entry)
  File "/garmindb/lib/python3.11/site-packages/idbutils/db_object.py", line 297, in s_insert_or_update
    instance = cls.s_get_from_dict(session, values_dict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/garmindb/garmindb/monitoring_db.py", line 44, in s_get_from_dict
    return session.query(cls).filter(cls.timestamp == values_dict['timestamp']).filter(cls.activity_type == values_dict['activity_type']).one_or_none()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2785, in one_or_none
    return self._iter().one_or_none()  # type: ignore
           ^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2857, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
           ^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1817, in _execute_context
    self._handle_dbapi_exception(
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1811, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1483, in _init_compiled
    l_param: List[Any] = [
                         ^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1485, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1806, in process
    value = self._db_value_for_elem(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/garmindb/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1670, in _db_value_for_elem
    raise LookupError(
sqlalchemy.exc.StatementError: (builtins.LookupError) '<UnknownEnumValue.UnknownEnumValue_13: 13>' is not among the defined enum values. Enum name: activitytype. Possible values: generic, running, cycling, ..., invalid
[SQL: SELECT monitoring_info.timestamp AS monitoring_info_timestamp, monitoring_info.file_id AS monitoring_info_file_id, monitoring_info.activity_type AS monitoring_info_activity_type, monitoring_info.resting_metabolic_rate AS monitoring_info_resting_metabolic_rate, monitoring_info.cycles_to_distance AS monitoring_info_cycles_to_distance, monitoring_info.cycles_to_calories AS monitoring_info_cycles_to_calories 
FROM monitoring_info 
WHERE monitoring_info.timestamp = ? AND monitoring_info.activity_type = ?]
[parameters: [{}]]__

The line in the fit file is as follows:

> Definition,5,monitoring_info,timestamp,1,,local_timestamp,1,,cycles_to_distance,3,,cycles_to_calories,3,,unknown,4,,resting_metabolic_rate,1,,activity_type,3,,unknown,1,,
> Data,5,monitoring_info,timestamp,"1135361100",s,local_timestamp,"1135364700",s,cycles_to_distance,"1.6652|2.4978|2.0",m/cycle,cycles_to_calories,"0.07|0.2208|0.0",kcal/cycle,unknown,"7500|7500|2000|2000",,resting_metabolic_rate,"2316",kcal / day,activity_type,"6|1|13",,,,,

If I check my activity data on Garmin Connect there is no activity at this time, just normal heartrate and steps.

**Comment by zuavra** [comment]
I'm getting something similar I think with 3.8.0:

```
Failed to write message <MessageType.monitoring_info: 103> type DataMessage(<MessageType.monitoring_info: 103>: [timestamp(datetime.datetime(2025, 8, 9, 7, 39, tzinfo=datetime.timezone.utc) (1123659540)), local_timestamp(datetime.datetime(2025, 8, 9, 10, 39) (1123670340)), cycles_to_distance([1.5652, 2.3478, 2.0] m/cycle ([7826, 11739, 10000])), cycles_to_calories([0.06116025181289345, 0.19304327038010996, 0.0] kcal/cycle ([307, 969, 0])), unknown_7([7500.0, 5030.0, 2000.0, 2000.0]), resting_metabolic_rate(2213.0 kcal/day), activity_type([<ActivityType.walking: 6>, <ActivityType.running: 1>, <UnknownEnumValue.UnknownEnumValue_13: 13>] ([6, 1, 13])), unknown_8([invalid] (255))]): (builtins.LookupError) '<UnknownEnumValue.UnknownEnumValue_13: 13>' is not among the defined enum values. Enum name: activitytype. Possible values: generic, running, cycling, ..., invalid
[SQL: SELECT monitoring_info.timestamp AS monitoring_info_timestamp, monitoring_info.file_id AS monitoring_info_file_id, monitoring_info.activity_type AS monitoring_info_activity_type, monitoring_info.resting_metabolic_rate AS monitoring_info_resting_metabolic_rate, monitoring_info.cycles_to_distance AS monitoring_info_cycles_to_distance, monitoring_info.cycles_to_calories AS monitoring_info_cycles_to_calories 
FROM monitoring_info 
WHERE monitoring_info.timestamp = ? AND monitoring_info.activity_type = ?]
[parameters: [{}]]
```
