### ISSUE TITLE
AssertionError on attempting to run garmindb_cli.py script

### ISSUE THREAD

**Issue by lowebb** [tcgoetz/GarminDB#249]
**Describe the bug**
Since the 25/11/2024, attempting to pull data from Garmin is throwing an AssertionError when attempting to login

This happens for entire pull or just the latest. I've checked and re-checked my auth details and am lost what the problem might be. Any help much appreciated

**To Reproduce**
1. Run script per README.md `garmindb_cli.py --all --download --import --analyze`
3. It fails

**Expected behavior**
It should run, download data and exit

**Logs**
```
garmindb_cli.py --all --download --import --analyze
___Downloading All Data___
Traceback (most recent call last):
  File "/home/xxxxxxxx/fw/garmin/venv2/bin/garmindb_cli.py", line 368, in <module>
    main(sys.argv[1:])
  File "/home/xxxxxx/fw/garmin/venv2/bin/garmindb_cli.py", line 349, in main
    download_data(args.overwrite, args.latest, args.stats)
  File "/home/xxxxxxxx/fw/garmin/venv2/bin/garmindb_cli.py", line 113, in download_data
    if not download.login():
  File "/home/xxxxxxxx/fw/garmin/venv2/lib/python3.10/site-packages/garmindb/download.py", line 92, in login
    self.garth.username
  File "/home/xxxxxxx/fw/garmin/venv2/lib/python3.10/site-packages/garth/http.py", line 109, in username
    return self.profile["userName"]
  File "/home/xxxxxxx/fw/garmin/venv2/lib/python3.10/site-packages/garth/http.py", line 104, in profile
    assert isinstance(self._profile, dict)
AssertionError
```

**Please run bugreport.sh and attach bugreport.zip.**

**Additional context**

**Comment by tcgoetz** [comment]
This is a bug in garth: https://github.com/matin/garth/issues/73

**Comment by tcgoetz** [comment]
Waiting on this PR https://github.com/matin/garth/pull/74 and a new release of garth with it in it. New release of GarminDB when that happens.

**Comment by cyberjunky** [comment]
@tcgoetz I temp fixed it in python-garminconnect by doing this before/in my code, maybe you can do something similar in your code?
```

# Temp fix for API change!
garth.http.USER_AGENT = {"User-Agent": "GCM-iOS-5.7.2.1"}
```

https://github.com/cyberjunky/python-garminconnect/blob/master/garminconnect/__init__.py#L15
