### ISSUE TITLE
Missing Test Data

### ISSUE THREAD

**Issue by fjih** [tcgoetz/GarminDB#251]
**Describe the bug**
Test failures running `make test`
Looks like a couple missing folders and maybe some test data files as well.

**To Reproduce**
Execute `make test`

**Expected behavior**
Passing tests on a clean clone, 20241204

**Logs**
Missing test/test_data/fit/activity and test/test_data/fit/sleep
```
======================================================================
ERROR: test_sleep_import (__main__.TestGarminDb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fjih/git/External/GarminDB/test/test_garmin_db.py", line 126, in test_sleep_import
    gfd = GarminSleepFitData('test_files/fit/sleep', latest=False, measurement_system=self.measurement_system, debug=2)
  File "/home/fjih/.local/lib/python3.10/site-packages/garmindb/import_monitoring.py", line 93, in __init__
    super().__init__(input_dir, debug, latest, True, [fitfile.FileType.sleep], measurement_system)
  File "/home/fjih/.local/lib/python3.10/site-packages/garmindb/fit_data.py", line 41, in __init__
    self.file_names = FileProcessor.dir_to_files(input_dir, fitfile.file.name_regex, latest, recursive)
  File "/home/fjih/.local/lib/python3.10/site-packages/idbutils/file_processor.py", line 46, in dir_to_files
    for file in os.listdir(input_dir):
FileNotFoundError: [Errno 2] No such file or directory: 'test_files/fit/sleep'

```

```
======================================================================
ERROR: test_fit_file_import (__main__.TestActivitiesDb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fjih/git/External/GarminDB/test/test_activities_db.py", line 121, in test_fit_file_import
    self.fit_file_import()
  File "/home/fjih/git/External/GarminDB/test/test_activities_db.py", line 95, in fit_file_import
    self.profile_function('fit_activities_import', self.__fit_file_import)
  File "/home/fjih/git/External/GarminDB/test/test_db_base.py", line 25, in profile_function
    pr.runcall(func, *args)
  File "/usr/lib/python3.10/cProfile.py", line 110, in runcall
    return func(*args, **kw)
  File "/home/fjih/git/External/GarminDB/test/test_activities_db.py", line 89, in __fit_file_import
    gfd = GarminActivitiesFitData('test_files/fit/activity', latest=False, measurement_system=self.measurement_system, debug=2)
  File "/home/fjih/.local/lib/python3.10/site-packages/garmindb/activities_fit_data.py", line 29, in __init__
    super().__init__(input_dir, debug, latest, False, [fitfile.FileType.activity], measurement_system)
  File "/home/fjih/.local/lib/python3.10/site-packages/garmindb/fit_data.py", line 41, in __init__
    self.file_names = FileProcessor.dir_to_files(input_dir, fitfile.file.name_regex, latest, recursive)
  File "/home/fjih/.local/lib/python3.10/site-packages/idbutils/file_processor.py", line 46, in dir_to_files
    for file in os.listdir(input_dir):
FileNotFoundError: [Errno 2] No such file or directory: 'test_files/fit/activity'

```

After adding these directories failures to check tables. Not sure if this is due to missing test data files in said missing directories.
```
======================================================================
FAIL: test_db_tables_exists (__main__.TestActivitiesDb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fjih/git/External/GarminDB/test/test_db_base.py", line 46, in test_db_tables_exists
    self.check_db_tables_exists(self.db, self.table_dict)
  File "/home/fjih/git/External/GarminDB/test/test_db_base.py", line 39, in check_db_tables_exists
    self.assertGreaterEqual(table.row_count(db), min_rows, 'table %s has no data' % table_name)
AssertionError: 0 not greater than or equal to 1 : table paddle_activities_table has no data

======================================================================
FAIL: test_file_import (__main__.TestActivitiesDb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fjih/git/External/GarminDB/test/test_activities_db.py", line 150, in test_file_import
    self.fit_file_import()
  File "/home/fjih/git/External/GarminDB/test/test_activities_db.py", line 96, in fit_file_import
    self.check_db_tables_exists(self.test_mon_db, {'device_table' : Device})
  File "/home/fjih/git/External/GarminDB/test/test_db_base.py", line 39, in check_db_tables_exists
    self.assertGreaterEqual(table.row_count(db), min_rows, 'table %s has no data' % table_name)
AssertionError: 0 not greater than or equal to 1 : table device_table has no data

======================================================================
FAIL: test_fit_file_import (__main__.TestActivitiesDb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fjih/git/External/GarminDB/test/test_activities_db.py", line 121, in test_fit_file_import
    self.fit_file_import()
  File "/home/fjih/git/External/GarminDB/test/test_activities_db.py", line 96, in fit_file_import
    self.check_db_tables_exists(self.test_mon_db, {'device_table' : Device})
  File "/home/fjih/git/External/GarminDB/test/test_db_base.py", line 39, in check_db_tables_exists
    self.assertGreaterEqual(table.row_count(db), min_rows, 'table %s has no data' % table_name)
AssertionError: 0 not greater than or equal to 1 : table device_table has no data

======================================================================
FAIL: test_garmin_act_db_tables_exists (__main__.TestActivitiesDb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fjih/git/External/GarminDB/test/test_activities_db.py", line 61, in test_garmin_act_db_tables_exists
    self.assertGreater(PaddleActivities.row_count(self.garmin_act_db), 0)
AssertionError: 0 not greater than 0

```

**Comment by fjih** [comment]
Looks like `/test_files/fit/unknown` is also missing for test `TestFitFile.test_parse_unknown`

**Comment by tcgoetz** [comment]
Test files are not checked in because they contain personal information. I will add the directories with a readme in them.

**Comment by tcgoetz** [comment]
Actually, the readme,txt files already exist.

**Comment by fjih** [comment]
Thanks Tom, but I'm not seeing them in the repo?

https://github.com/tcgoetz/GarminDB/tree/develop/test/test_files/fit

**Comment by tcgoetz** [comment]
https://github.com/tcgoetz/GarminDB/blob/master/test/test_files/fit/monitoring/readme.txt

**Comment by fjih** [comment]
Thanks Tom. Please see my original post.
The tests that are failing are looking for `activity`, `sleep`, and `unknown` subfolders under /test_files/fit.
