### ISSUE TITLE
Issue with build

### ISSUE THREAD

**Issue by ParzivalWins** [tcgoetz/GarminDB#31]
Hi. Getting the following error on latest Mac release. BTW, on the notes, it's copy_create_dbs.sh vs. create_dbs.sh listed in readme. (I'll do a PR if you want). Let me know.  

The path on my Garmin 530 is "Activities" not Activity.  

GarminDb_Darwin_1.0.5 ./copy_create_dbs.sh
Creating new DBs by copying from a USB mounted Garmin device
Copying activities files from /Volumes/GARMIN/GARMIN/ACTIVITY to /Users/juliemorris/HealthData/FitFiles/Activities
Traceback (most recent call last):
  File "garmin.py", line 344, in <module>
  File "garmin.py", line 331, in main
  File "garmin.py", line 72, in copy_data
  File "copy_garmin.py", line 37, in copy_activities
  File "file_processor.py", line 41, in dir_to_files
OSError: [Errno 2] No such file or directory: '/Volumes/GARMIN/GARMIN/ACTIVITY'
[21571] Failed to execute script garmin

Thanks.

**Comment by tcgoetz** [comment]
Is this working for you now?

**Comment by tcgoetz** [comment]
Closing. No response.
