### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by christian-ho** [tcgoetz/GarminDB#39]
After the latest update i'm getting the following error message:

Traceback (most recent call last):
  File "garmin.py", line 23, in <module>
    from import_garmin_activities import GarminJsonSummaryData, GarminJsonDetailsData, GarminActivitiesExtraData, GarminTcxData, GarminActivitiesFitData
  File "/home/christian/Projekte/GarminDB/import_garmin_activities.py", line 18, in <module>
    from garmin_db_tcx import GarminDbTcx
  File "/home/christian/Projekte/GarminDB/garmin_db_tcx.py", line 9, in <module>
    from Tcx import Tcx
ImportError: cannot import name 'Tcx'

**Comment by tcgoetz** [comment]
This should be fixed. This was a problem with a new submodule.

**Comment by christian-ho** [comment]
Works again, thank you!
