### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by christian-ho** [tcgoetz/GarminDB#47]
Just did an `make update` and got the following error:
```
error: Der Server lehnt Anfrage nach nicht angebotenem Objekt 80247380a47021ce37838251e704f75b48774d78 ab.
"fetch" in Submodul-Pfad 'Fit' ausgeführt, aber 80247380a47021ce37838251e704f75b48774d78 nicht enthalten. Direktes Anfordern dieses Commits ist fehlgeschlagen.
Makefile:45: recipe for target 'submodules_update' failed
make: *** [submodules_update] Error 1
```

When running `make` i get the following:
```
Traceback (most recent call last):
  File "garmin.py", line 387, in <module>
    main(sys.argv[1:])
  File "garmin.py", line 377, in main
    import_data(debug, latest, weight, monitoring, sleep, rhr, activities, test)
  File "garmin.py", line 218, in import_data
    gfd.process_files(db_params_dict)
  File "/home/christian/Projekte/GarminDB/fit_data.py", line 54, in process_files
    fp.write_file(fit_file)
  File "/home/christian/Projekte/GarminDB/fit_file_processor.py", line 83, in write_file
    self.__write_message_types(fit_file, fit_file.message_types())
  File "/home/christian/Projekte/GarminDB/fit_file_processor.py", line 71, in __write_message_types
    self.__write_message_type(fit_file, message_type)
  File "/home/christian/Projekte/GarminDB/fit_file_processor.py", line 57, in __write_message_type
    function(fit_file, message_type, messages)
  File "/home/christian/Projekte/GarminDB/fit_file_processor.py", line 46, in __write_generic
    function(fit_file, message_dict)
  File "/home/christian/Projekte/GarminDB/fit_file_processor.py", line 299, in _write_session_entry
    current.update_from_dict(activity, ignore_none=True, ignore_zero=True)
TypeError: update_from_dict() got an unexpected keyword argument 'ignore_zero'
```

**Comment by tcgoetz** [comment]
The update failed to update the FIT submodule. It says it couldn't find the 80247380a47021ce37838251e704f75b48774d78 commit for the submodule. It should be there. Here it is on GitHub: https://github.com/tcgoetz/Fit/commit/80247380a47021ce37838251e704f75b48774d78

Can you try the update again?

**Comment by christian-ho** [comment]
Weird, now it's working again!
