### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by joseccreis** [tcgoetz/GarminDB#85]
**Describe the bug**
I'm getting the following error message when I run the script download_create_dbs.sh 

"Traceback (most recent call last):
  File "garmin.py", line 340, in <module>
  File "garmin.py", line 321, in main
  File "garmin.py", line 125, in download_data
  File "garmin.py", line 71, in __get_date_and_days
TypeError: '<' not supported between instances of 'NoneType' and 'int'"
[15280] Failed to execute script garmin

**To Reproduce**

1. Download GarminDb_Darwin_1.8.0
2. Unzip file
3. Edit file GarminConnectConfig.json : Changed Password, username, and start date for data
4. From terminal ran download_create_dbs.sh

I'm running this on macOS High Sierra , v10.13.6

**Expected behavior**

No errors and database is created.
[garmin.log](https://github.com/tcgoetz/GarminDB/files/5506877/garmin.log)

**Logs**
Screen Log:

Creating new DBs by downloading from Garmin Connect
___Downloading All Data___
Geting activities: '/Users/josereis-work/HealthData/FitFiles/Activities' (1000) temp /var/folders/1k/w4rkpt_573z2kb7nvpy375280000gr/T/tmp6plial51
100%|█████████████████████████████████| 424/424 [13:12<00:00,  1.87s/activities]
Traceback (most recent call last):
  File "garmin.py", line 340, in <module>
  File "garmin.py", line 321, in main
  File "garmin.py", line 125, in download_data
  File "garmin.py", line 71, in __get_date_and_days
TypeError: '<' not supported between instances of 'NoneType' and 'int'
[15280] Failed to execute script garmin

Please include a copy of screen logging and garmin.log.

**Please run bugreport.sh and attach bugreport.zip.**

**Additional context**

**Comment by tcgoetz** [comment]
https://github.com/tcgoetz/GarminDB/releases/tag/v1.8.1
