### ISSUE TITLE
ImportError: cannot import name 'DbParams' from 'utilities' (unknown location)

### ISSUE THREAD

**Issue by raphaelfournier** [tcgoetz/GarminDB#89]
**Describe the bug**
I encounter a brutal stop from `make setup`shortly after starting. It seems to expect a `DbParams.py` file, from folder utilities, which is empty. it's a submodule, so that's normal after a non-recursive `git clone`. I tried to make a `--recursive` cloning, but it also fails (at `git submodule init`, perhaps because it has already been initialized in the recursive cloning?).

**Logs**

```
$ git clone git@github.com:tcgoetz/GarminDB.git
$ cd GarminDB
$ make setup
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/raph/.scripts/GarminDB/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
ImportError: cannot import name 'DbParams' from 'utilities' (unknown location)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/raph/.scripts/GarminDB/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
ImportError: cannot import name 'DbParams' from 'utilities' (unknown location)
git submodule init
make: git: Permission non accordée
make: *** [Makefile:51 : submodules_update] Erreur 127
```

**Additional context**
I work under ArchLinux, with zsh.

**Comment by raphaelfournier** [comment]
Well, I solved my problem by modifying the Makefile.

My solution was to perform a `git clone --recursive`, and remove the `update` directive triggered by the `setup` call (line 16). Then `make setup` only calls for `deps`, terminates well. I could then create the dbs and download data. Thanks for the tool, sorry for the noise.

**Comment by mkffl** [comment]
Could you please provide some details around the problem and your solution? I have the same error message but when I try your solution I get a new error.

Error when following the author's instructions:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/michel/Documents/pjs/garmin/GarminDB/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
ImportError: cannot import name 'DbParams' from 'utilities' (unknown location)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/michel/Documents/pjs/garmin/GarminDB/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
ImportError: cannot import name 'DbParams' from 'utilities' (unknown location)
```

How I understand your solution:
```git
git clone --recursive https://github.com/tcgoetz/GarminDB.git
#Remove line 16 of Makefile
make setup
```

New error
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/michel/Documents/pjs/garmin/GarminDBrecursive/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
  File "/Users/michel/Documents/pjs/garmin/GarminDBrecursive/utilities/__init__.py", line 11, in <module>
    from utilities.db import DbParams, DB
  File "/Users/michel/Documents/pjs/garmin/GarminDBrecursive/utilities/db.py", line 12, in <module>
    from sqlalchemy import create_engine
ModuleNotFoundError: No module named 'sqlalchemy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/michel/Documents/pjs/garmin/GarminDBrecursive/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
  File "/Users/michel/Documents/pjs/garmin/GarminDBrecursive/utilities/__init__.py", line 11, in <module>
    from utilities.db import DbParams, DB
  File "/Users/michel/Documents/pjs/garmin/GarminDBrecursive/utilities/db.py", line 12, in <module>
    from sqlalchemy import create_engine
ModuleNotFoundError: No module named 'sqlalchemy'
make: Nothing to be done for `setup'.
```

Interestingly, when I don't remove line 16 and I use the --recursive cloned repo, a lot more stuff happens when I run `make setup`, but then  I get

```
Collecting PyInstaller (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/9e/ed/fbdad7f5d8f794c901076b814b8e9f5ce31d32c0bc3b63ddd27b61db9530/pyinstaller-4.1.tar.gz
  Installing build dependencies ... error
  Complete output from command /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/yx/lm4rgmdj547ggft_1frhm6y40000gp/T/pip-build-env-c8rjohj7/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.8.0 wheel:
  Collecting setuptools>=40.8.0
    Using cached https://files.pythonhosted.org/packages/34/b6/33396512781ec5c40de2e70e8a68f2d0c4d91d6cc182410788c34a00002d/setuptools-51.1.1-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
  Installing collected packages: setuptools, wheel
  Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7'
  Consider using the `--user` option or check the permissions.
```

This repo looks amazing, such a shame that it's so hard to install the solution. If I manage to install it would be great to publish it in a containerised version for others to not go through the same pains.

**Comment by raphaelfournier** [comment]
My comment was a bit too quick. I did not mean "remove line 16 from the Makefile", but "remove the `update` directive from line 16". So that line 16 goes from `setup: update deps` to `setup: deps`. The `deps` directive should install sqlalchemy, mentioned in the file `requirements.txt` (called by `deps`).

**Comment by mkffl** [comment]
Thanks for clarifying. I have given up on my host machine installation and used a docker container with a light Ubuntu image. It works like a charm.
