### ISSUE TITLE
Graphs shows emty pages

### ISSUE THREAD

**Issue by Gronertw** [tcgoetz/GarminDB#90]
Hi,
I'm using PY Version 3.7.3 on Raspberry PI4. I've cloned GarminDB via Github Desktop. 
make create_dbs seems tu run ok. But starting: make graphs , only shows one empty Graph of Heart Rate by weeks. Thats all.
This is the Monitor output:

pi@PI4-Home-NAS-1:~/GarminDB $ make graphs
/usr/bin/python3 graphs.py --all
Traceback (most recent call last):
  File "graphs.py", line 304, in <module>
    main(sys.argv[1:])
  File "graphs.py", line 291, in main
    graph.graph_activity('itime', args.period, args.days)
  File "graphs.py", line 208, in graph_activity
    graph_func(time, data, period)
  File "graphs.py", line 181, in _graph_itime
    itime_goal_max = max([entry.intensity_time_goal_mins for entry in data])
ValueError: max() arg is an empty sequence
make: *** [Makefile:109: graphs] Error 1

What is the problem?

**Comment by Gronertw** [comment]
Hi, the problem is resolved. It was the format of _start_date  entry's in the "GarminConnectConfig.json."
In my region the format normaly is dd/mm/yyyy. In the "GarminConnectConfig.json." it is mm/dd/yyyy.
